name: Fetch JSON Updates
on:
  schedule:
    # run once a day
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  fetch-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Set Git Config
        run: |
          git config pull.rebase false
          git config --global user.email "fetch-workflow@caniemail.com"
          git config --global user.name "Fetch Workflow"
          git remote set-url origin https://github.com/${{ github.repository }}

      # - name: Checkout Main
      #   run: |
      #     git fetch origin
      #     git branch -f main origin/main

      - name: Setup
        uses: ./.github/actions/setup

      - name: Fetch
        run: ./scripts/update-data.sh
